# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_address', models.CharField(max_length=2000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-event_date',),
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='InterestedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Events')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
    ]
