# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181121_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blog_image', models.URLField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name': 'Blog Categories',
                'verbose_name_plural': 'Blo gCategories',
            },
        ),
        migrations.AlterModelOptions(
            name='interestedevent',
            options={'ordering': ('-created_date',), 'verbose_name': 'Interested Event', 'verbose_name_plural': 'Interested Event'},
        ),
    ]
