# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181121_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('blog_image', models.URLField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'ordering': ('-created_date',), 'verbose_name': 'Blog Categories', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BlogCategories'),
        ),
    ]
