# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181121_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
