# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181121_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPollution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name': 'Air Pollution',
                'verbose_name_plural': 'Air Pollution',
            },
        ),
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('display_text', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name': 'Air Quality',
                'verbose_name_plural': 'Air Quality',
            },
        ),
    ]
