# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_airpollution_airquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='airquality',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategories',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
