# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181121_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'verbose_name': 'Air Pollution',
                'verbose_name_plural': 'Air Pollution',
            },
        ),
        migrations.RemoveField(
            model_name='airpollution',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='airpollution',
            name='location',
        ),
        migrations.RemoveField(
            model_name='airpollution',
            name='longitude',
        ),
        migrations.AddField(
            model_name='airpollution',
            name='towers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Towers'),
            preserve_default=False,
        ),
    ]
